### ISSUE TITLE
Feedback & Questions

### ISSUE THREAD

**Issue by jeffberry** [skylerfenn/nvmrc-check#1]
Hey Skyler,

This looks cool, it's definitely in the spirit of modern javascript and micro-libraries! I got a couple questions that I'm just curious about and might help you extend this further, note that I've never personally used a `.nvmrc` file so these questions are just my thoughts, but here they are:

1) Is this a package that would be installed per-project, or is it intended to be installed globally?
2) If it's meant to run on "postinstall", isn't that already too late to detect the node version that is installing it? I see that it would still exit out, but by the time it exits wouldn't all the packages have already installed? Obviously "preinstall" would be too early as this package would not be installed yet to execute - also part of why I asked if this was to be installed per-project or globally.
3) How does this supplement the "engines" property package.json already allows and/or how does this replace what that is missing? https://docs.npmjs.com/files/package.json#engines
4) What is node's default support for a `.nvmrc` file missing that you were trying to augment?
5) Is the `.bash_profile` edit necessary, or is that optional? The way I understood the `.nvmrc` file is that if you had one with a version number defined in it - node would automatically use that version from that directory. 

Good job though, this is definitely a clever way to use Javascript in a command line way that you wouldn't typically thing to do because we always see JS as web based. Good job and keep building your library! Stealing the format of another good package's README will be important too in order to gain adoption of your packages. I usually don't even install or try a package if it doesn't have a good README. It should tell me how to install the package, what problem it solves, etc.

**Comment by skylerfenn** [comment]
1 - 2. I was thinking the package could be installed per project. I like the idea of making it globally required though. Preinstall failure seems more helpful.
3. I could incorporate the "engines" property as an alternative option. I like the functionality `.nvmrc` brings since it's part of nvm. Also, I didn't want to have to specify the version in both the "engines" and `.nvmrc`.
4. Node doesn't support the `.nvmrc` file. It is an part of nvm. I was trying to require a node version for a project with automated version switching functionality.
5. The [`.nvrmrc`](https://github.com/creationix/nvm#nvmrc) version isn't automatically used. The `.bash_profile` suggestion makes the node version switch automatically with nvm when entering a folder with an `.nvmrc`. 

Thanks for the feedback and thoughts. Very helpful! I've got some ideas on what I can change.

**Comment by jeffberry** [comment]
Ahh okay - that makes sense on the `.nvmrc`. I think it's a great idea to have it switch to the proper node version when you enter a project. That's really cool.

One thing you might try: instead of requiring me to make an edit to *my* "postinstall" script, couldn't you include that "postinstall" snippet into *your* package's package.json instead? So all I have to do is install your package and it automatically does the check for me without requiring edits.

All you have to do is move this snippet (and fix the syntax to proper JSON 😛):

```scripts {
  "postinstall": "nvmrc-check --node $(cat .nvmrc)"
}```

**Comment by skylerfenn** [comment]
Sweet, check out the bash script in this package's readme. I just edited it. It's modeled after nvm's zsh example in their readme. It works super well switching node automatically based on .nvmrc!

I'll definitely see about adding the "postinstall" to my package.json. That's a great idea. 

Appreciate the feedback!
